### PR TITLE
Really make the mod compatible with 1.17

### PR DESCRIPTION
**Pull request by mooziii**
You marked the mod as compatible with 1.17 but its actually not as it requires java 17 but minecraft 1.17 uses java 16

### CODE REVIEW

**Comment by OffsetMonkey538** [comment]
Sorry about that! After I released it, I thought that might be a problem but then forgot and didn't check.
Don't versions below 1.17 actually use java 8?

**Comment by mooziii** [comment]
Versions below 1.17 still use java 8 yes

**Comment by OffsetMonkey538** [comment]
So would it make sense to lower the version to java 8?

**Comment by mooziii** [comment]
I don't know whether its java `1.8` or `8` in fabric.mod.json so i decided to just completely remove the java dependency.

**Comment by OffsetMonkey538** [comment]
Yeah that's fine

**Comment by OffsetMonkey538** [comment]
I messed something up withe the workflows

**Comment by OffsetMonkey538** [comment]
Loom 12 requires java 17 it seems. Well it's probably not important anyway

**Comment by OffsetMonkey538** [comment]
Right, that's a java 16 feature

**Comment by OffsetMonkey538** [comment]
Finally!

**Comment by OffsetMonkey538** [comment]
I'm gonna download 1.15 and test if it works

**Comment by OffsetMonkey538** [comment]
It seems to work

**Comment by OffsetMonkey538** [comment]
Thank you!

**Pull request merged**
